name: hvatai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ^3.27.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  internet_connection_checker: ^1.0.0+1
  mask_text_input_formatter: ^2.5.0 
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  multi_image_picker2: ^5.0.02
  geolocator: ^11.0.0
  geocoding: ^4.0.0
  dotted_border: ^2.0.0
  google_sign_in: ^6.1.5
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  one_context: ^4.0.0
  auto_route: ^9.3.0+1
  json_annotation: ^4.9.0
  country_picker: ^2.0.21
  flutter_local_notifications: ^18.0.1
  persistent_bottom_nav_bar: ^6.2.1
  permission_handler: ^11.3.1
  go_router: ^14.8.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  device_preview: ^1.2.0
  simple_gradient_text: ^1.3.0
  google_fonts: ^6.2.1
  freezed_annotation: ^2.4.4
  easy_localization: ^3.0.7+1
  cached_network_image: ^3.4.1
  provider: ^6.1.4
  flutter_localizations:
    sdk: flutter
  dropdown_button2: ^2.3.9
  pinput: ^5.0.1
  responsive_grid_list: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^2.4.6


flutter_assets:
  assets_path: assets/
  output_path: lib/core/theme
  filename: assets.dart

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/


  fonts:
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
          weight: 700
  
  generate: true
