import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/svg.dart';
import 'package:go_router/go_router.dart';
import 'package:hvatai/core/customs/customs.dart';
import 'package:hvatai/core/extensions/size_extension.dart';
import 'package:hvatai/core/theme/app_colors.dart';
import 'package:hvatai/core/theme/assets.dart';
import 'package:hvatai/features/auth/data/models/registration_model/user_registration_data.dart';
import 'package:hvatai/features/address/presentation/cubit/delivery_address/delivery_address_cubit.dart';
import 'package:hvatai/features/address/presentation/cubit/edit_address/edit_address_cubit.dart';
import 'package:hvatai/locator.dart';
import 'package:hvatai/routes/app_routes.dart';

part 'screens/init_new_address_screen.dart';
part 'screens/add_delivery_address_screen.dart';
part 'screens/edit_delivery_address_screen.dart';
