// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_TCqrxRcekCICD2Uf-pTdEVwFyFBbsI0',
    appId: '1:447608090352:web:7f7727d304657159d49c35',
    messagingSenderId: '447608090352',
    projectId: 'stream-984ab',
    authDomain: 'stream-984ab.firebaseapp.com',
    storageBucket: 'stream-984ab.firebasestorage.app',
    measurementId: 'G-ZXCNKND8WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNO3DYdtBaSCFevxVDKXjXGaPDAIGEzrk',
    appId: '1:447608090352:android:0a1ffb7bbb2949f2d49c35',
    messagingSenderId: '447608090352',
    projectId: 'stream-984ab',
    storageBucket: 'stream-984ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx-vGVZ2B5k4qUIAuOwl9oIjVDpgd2hIU',
    appId: '1:447608090352:ios:0f2d435d8db00f87d49c35',
    messagingSenderId: '447608090352',
    projectId: 'stream-984ab',
    storageBucket: 'stream-984ab.firebasestorage.app',
    androidClientId: '447608090352-69cdsnjpuu3ckmvn6n7le4r8dptsrqsn.apps.googleusercontent.com',
    iosClientId: '447608090352-2aho7s9rgrgird65qk123nd22750lbt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hvatai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx-vGVZ2B5k4qUIAuOwl9oIjVDpgd2hIU',
    appId: '1:447608090352:ios:0f2d435d8db00f87d49c35',
    messagingSenderId: '447608090352',
    projectId: 'stream-984ab',
    storageBucket: 'stream-984ab.firebasestorage.app',
    androidClientId: '447608090352-69cdsnjpuu3ckmvn6n7le4r8dptsrqsn.apps.googleusercontent.com',
    iosClientId: '447608090352-2aho7s9rgrgird65qk123nd22750lbt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hvatai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_TCqrxRcekCICD2Uf-pTdEVwFyFBbsI0',
    appId: '1:447608090352:web:9ec31e6b444a71e3d49c35',
    messagingSenderId: '447608090352',
    projectId: 'stream-984ab',
    authDomain: 'stream-984ab.firebaseapp.com',
    storageBucket: 'stream-984ab.firebasestorage.app',
    measurementId: 'G-1T37LRWGSY',
  );

}