import 'package:hvatai/features/auth/domain/usecases/add_fav_category_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/check_otp_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/delivery_address_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/get_category_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/get_fav_category_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/login_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/login_with_apple_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/login_with_google_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/register_usecase.dart';
import 'package:hvatai/features/home/domain/usecases/get_notification_usecase.dart';
import 'package:hvatai/features/home/domain/usecases/get_streams_usecases.dart';
import 'package:hvatai/features/home/domain/usecases/join_stream_usecase.dart';
import 'package:hvatai/features/home/domain/usecases/mark_read_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/add_new_address_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/add_new_card_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/add_new_product_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/create_stream_uscecase.dart';
import 'package:hvatai/features/profile/domain/usecases/delete_account_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/delete_address_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/delete_card_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/edit_delivery_address_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/get_card_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/get_delivery_address_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/get_my_products_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/get_product_category_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/get_profile_data_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/sign_out_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/update_profile_data_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/update_profile_type_usecase.dart';
import 'package:hvatai/locator.dart';

void locatorUseCase() {
  // //UseCase
  locator.registerLazySingleton(() => LoginUseCase(locator()));
  locator.registerLazySingleton(() => RegisterUseCase(locator()));
  locator.registerLazySingleton(() => CheckOtpUseCase(locator()));
  locator.registerLazySingleton(() => DeliveryAddressUseCase(locator()));
  locator.registerLazySingleton(() => LoginWithGoogleUseCase(locator()));
  locator.registerLazySingleton(() => GetProfileDataUsecase(locator()));
  locator.registerLazySingleton(() => UpdateProfileDataUsecase(locator()));
  locator.registerLazySingleton(() => GetDeliveryAddressUsecase(locator()));
  locator.registerLazySingleton(() => AddNewAddressUsecase(locator()));
  locator.registerLazySingleton(() => EditDeliveryAddressUsecase(locator()));
  locator.registerLazySingleton(() => GetCardUsecase(locator()));
  locator.registerLazySingleton(() => GetNotificationUsecase(locator()));
  locator.registerLazySingleton(() => AddNewCardUsecase(locator()));
  locator.registerLazySingleton(() => DeleteAccountUsecase(locator()));
  locator.registerLazySingleton(() => SignOutUsecase(locator()));
  locator.registerLazySingleton(() => DeleteAddressUsecase(locator()));
  locator.registerLazySingleton(() => DeleteCardUsecase(locator()));
  locator.registerLazySingleton(() => GetCategoryUsecase(locator()));
  locator.registerLazySingleton(() => AddFavCategoryUsecase(locator()));
  locator.registerLazySingleton(() => GetFavCategoryUsecase(locator()));
  locator.registerLazySingleton(() => MarkReadUsecase(locator()));
  locator.registerLazySingleton(() => LoginWithAppleUsecase(locator()));
  locator.registerLazySingleton(() => UpdateProfileTypeUsecase(locator()));
  locator.registerLazySingleton(() => GetMyProductsUsecase(locator()));
  locator.registerLazySingleton(() => GetProductCategoryUsecase(locator()));
  locator.registerLazySingleton(() => AddNewProductUsecase(locator()));
  locator.registerLazySingleton(() => CreateStreamUsecase(locator()));
  locator.registerLazySingleton(() => GetLiveStreamsUsecase(locator()));
  locator.registerLazySingleton(() => GetStreamsUsecase(locator()));
  locator.registerLazySingleton(() => JoinStreamUsecase(locator()));
}
