import 'package:hvatai/features/cart/domain/usecases/add_fav_product_usecase.dart';
import 'package:hvatai/features/cart/domain/usecases/add_product_to_cart_usecase.dart';
import 'package:hvatai/features/cart/domain/usecases/create_order_usecase.dart';
import 'package:hvatai/features/cart/domain/usecases/delete_cart_usecase.dart';
import 'package:hvatai/features/cart/domain/usecases/get_all_products_usecase.dart';
import 'package:hvatai/features/cart/domain/usecases/get_cart_usecase.dart';
import 'package:hvatai/features/activity/domain/usecases/get_favorites_usecase.dart';
import 'package:hvatai/features/activity/domain/usecases/get_user_bids_usecase.dart';
import 'package:hvatai/features/review/domain/usecases/submit_review_usecase.dart';
import 'package:hvatai/features/favorites/domain/usecases/get_fav_products_usecase.dart';
import 'package:hvatai/features/cart/domain/usecases/update_cart_usecase.dart';
import 'package:hvatai/features/add_new_product/domain/usecases/add_new_product_usecase.dart';
import 'package:hvatai/features/add_new_product/domain/usecases/update_product_usecase.dart';
import 'package:hvatai/features/add_new_product/domain/usecases/get_product_category_usecase.dart';
import 'package:hvatai/features/add_new_product/domain/usecases/get_last_used_categories_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/add_fav_category_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/check_otp_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/get_category_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/get_fav_category_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/send_otp_usecase.dart';
import 'package:hvatai/features/auth/domain/usecases/update_name_usecase.dart';
import 'package:hvatai/features/change_password/domain/usecases/change_password_usecase.dart';
import 'package:hvatai/features/chat/domain/usecases/get_chats_usecase.dart';
import 'package:hvatai/features/chat/domain/usecases/get_messages_usecase.dart';
import 'package:hvatai/features/chat/domain/usecases/get_support_chat_usecase.dart';
import 'package:hvatai/features/chat/domain/usecases/get_support_messages_usecase.dart';
import 'package:hvatai/features/chat/domain/usecases/mark_as_read_usecase.dart';
import 'package:hvatai/features/chat/domain/usecases/send_message.dart';
import 'package:hvatai/features/chat/domain/usecases/send_support_messages_usecase.dart';
import 'package:hvatai/features/home/domain/usecases/get_live_streams_usecases.dart';
import 'package:hvatai/features/home/domain/usecases/get_streams_usecases.dart';
import 'package:hvatai/features/home/domain/usecases/join_stream_usecase.dart';
import 'package:hvatai/features/notifications/domain/usecases/get_notification_usecase.dart';
import 'package:hvatai/features/notifications/domain/usecases/mark_read_usecase.dart';
import 'package:hvatai/features/awards/domain/usecases/send_reward_usecase.dart';
import 'package:hvatai/features/home/domain/usecases/watch_live_streams_usecase.dart';
import 'package:hvatai/features/orders/domain/usecases/get_user_orders_usecase.dart';
import 'package:hvatai/features/address/domain/usecases/add_new_address_usecase.dart';
import 'package:hvatai/features/address/domain/usecases/delete_address_usecase.dart';
import 'package:hvatai/features/address/domain/usecases/edit_delivery_address_usecase.dart';
import 'package:hvatai/features/address/domain/usecases/get_delivery_address_usecase.dart';
import 'package:hvatai/features/payment_method/domain/usecases/add_new_card_usecase.dart';
import 'package:hvatai/features/payment_method/domain/usecases/delete_card_usecase.dart';
import 'package:hvatai/features/payment_method/domain/usecases/get_card_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/create_stream_uscecase.dart';
import 'package:hvatai/features/profile/domain/usecases/delete_account_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/get_my_products_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/get_profile_data_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/sign_out_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/update_profile_data_usecase.dart';
import 'package:hvatai/features/profile/domain/usecases/update_profile_type_usecase.dart';
import 'package:hvatai/features/company/domain/usecases/get_company_products_usecase.dart';
import 'package:hvatai/features/company/domain/usecases/get_company_streams_usecase.dart';
import 'package:hvatai/features/company/domain/usecases/get_user_data_usecase.dart';
import 'package:hvatai/features/search/domain/usecases/search_usecase.dart';
import 'package:hvatai/features/search/domain/usecases/search_suggestions_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/add_product_to_stream_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/add_stream_bids_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/end_stream_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/get_bid_session_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/get_stream_bids_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/get_stream_comments_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/get_stream_products_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/leave_stream_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/send_stream_comment_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/start_stream_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/toggle_bidding_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/get_subscribed_users_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/toggle_subscription_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/get_my_streams_usecase.dart';
import 'package:hvatai/features/stream/domain/usecases/update_stream_media_usecase.dart';
import 'package:hvatai/features/wallet/domain/usecases/get_wallet_transactions_usecase.dart';
import 'package:hvatai/features/wallet/domain/usecases/get_wallet_usecase.dart';
import 'package:hvatai/features/wallet/domain/usecases/withdraw_to_card_usecase.dart';
import 'package:hvatai/features/analytics/domain/usecases/get_statistics_usecase.dart';
import 'package:hvatai/locator.dart';

void locatorUseCase() {
  // //UseCase
  locator.registerLazySingleton(() => SendOtpUseCase(locator()));
  locator.registerLazySingleton(() => UpdateNameUseCase(locator()));
  locator.registerLazySingleton(() => CheckOtpUseCase(locator()));
  locator.registerLazySingleton(() => GetProfileDataUsecase(locator()));
  locator.registerLazySingleton(() => UpdateProfileDataUsecase(locator()));
  locator.registerLazySingleton(() => GetDeliveryAddressUsecase(locator()));
  locator.registerLazySingleton(() => AddNewAddressUsecase(locator()));
  locator.registerLazySingleton(() => EditDeliveryAddressUsecase(locator()));
  locator.registerLazySingleton(() => GetCardUsecase(locator()));
  locator.registerLazySingleton(() => GetNotificationUsecase(locator()));
  locator.registerLazySingleton(() => AddNewCardUsecase(locator()));
  locator.registerLazySingleton(() => DeleteAccountUsecase(locator()));
  locator.registerLazySingleton(() => SignOutUsecase(locator()));
  locator.registerLazySingleton(() => DeleteAddressUsecase(locator()));
  locator.registerLazySingleton(() => DeleteCardUsecase(locator()));
  locator.registerLazySingleton(() => GetCategoryUsecase(locator()));
  locator.registerLazySingleton(() => AddFavCategoryUsecase(locator()));
  locator.registerLazySingleton(() => GetFavCategoryUsecase(locator()));
  locator.registerLazySingleton(() => MarkReadUsecase(locator()));
  locator.registerLazySingleton(() => UpdateProfileTypeUsecase(locator()));
  locator.registerLazySingleton(() => GetMyProductsUsecase(locator()));
  locator.registerLazySingleton(() => GetAllProductsUsecase(locator()));
  locator.registerLazySingleton(() => GetProductCategoryUsecase(locator()));
  locator.registerLazySingleton(() => GetLastUsedCategoriesUsecase(locator()));
  locator.registerLazySingleton(() => AddNewProductUsecase(locator()));
  locator.registerLazySingleton(() => UpdateProductUsecase(locator()));
  locator.registerLazySingleton(() => SearchUsecase(locator()));
  locator.registerLazySingleton(() => SearchSuggestionsUsecase(locator()));
  locator.registerLazySingleton(() => GetUserDataUsecase(locator()));
  locator.registerLazySingleton(() => CreateStreamUsecase(locator()));
  locator.registerLazySingleton(() => AddFavProductUsecase(locator()));
  locator.registerLazySingleton(() => GetFavProductsUsecase(locator()));
  locator.registerLazySingleton(() => GetFavoritesUsecase(locator()));
  locator.registerLazySingleton(() => GetUserBidsUsecase(locator()));
  locator.registerLazySingleton(() => SubmitReviewUsecase(locator()));
  locator.registerLazySingleton(() => AddProductToCartUsecase(locator()));
  locator.registerLazySingleton(() => GetCartUsecase(locator()));
  locator.registerLazySingleton(() => UpdateCartUsecase(locator()));
  locator.registerLazySingleton(() => DeleteCartUsecase(locator()));
  locator.registerLazySingleton(() => GetLiveStreamsUsecase(locator()));
  locator.registerLazySingleton(() => GetStreamsUsecase(locator()));
  locator.registerLazySingleton(() => WatchLiveStreamsUsecase(locator()));
  locator.registerLazySingleton(() => JoinStreamUsecase(locator()));
  locator.registerLazySingleton(() => GetCompanyProductsUsecase(locator()));
  locator.registerLazySingleton(() => SendRewardUsecase(locator()));
  locator.registerLazySingleton(() => GetSupportChatUseCase(locator()));
  locator.registerLazySingleton(() => GetSupportMessagesUseCase(locator()));
  locator.registerLazySingleton(() => SendSupportMessagesUseCase(locator()));
  locator.registerLazySingleton(() => GetChatsUseCase(locator()));
  locator.registerLazySingleton(() => GetMessagesUseCase(locator()));
  locator.registerLazySingleton(() => SendMessageUseCase(locator()));
  locator.registerLazySingleton(() => MarkMessageAsReadUseCase(locator()));
  locator.registerLazySingleton(() => GetStreamCommentsUsecase(locator()));
  locator.registerLazySingleton(() => SendStreamCommentUsecase(locator()));
  locator.registerLazySingleton(() => LeaveStreamUsecase(locator()));
  locator.registerLazySingleton(() => EndStreamUsecase(locator()));
  locator.registerLazySingleton(() => GetStreamBidsUsecase(locator()));
  locator.registerLazySingleton(() => AddStreamBidUsecase(locator()));
  locator.registerLazySingleton(() => StartStreamUsecase(locator()));
  locator.registerLazySingleton(() => AddProductToStreamUsecase(locator()));
  locator.registerLazySingleton(() => GetStreamProductsUsecase(locator()));
  locator.registerLazySingleton(() => GetBidSessionUsecase(locator()));
  locator.registerLazySingleton(() => ToggleBiddingUsecase(locator()));
  locator.registerLazySingleton(() => GetSubscribedUsersUsecase(locator()));
  locator.registerLazySingleton(() => ToggleSubscriptionUsecase(locator()));
  locator.registerLazySingleton(() => GetMyStreamsUsecase(locator()));
  locator.registerLazySingleton(() => ChangePasswordUsecase(locator()));
  locator.registerLazySingleton(() => GetWalletUsecase(locator()));
  locator.registerLazySingleton(() => GetWalletTransactionsUsecase(locator()));
  locator.registerLazySingleton(() => WithdrawToCardUsecase(locator()));
  locator.registerLazySingleton(() => UpdateStreamMediaUsecase(locator()));
  locator.registerLazySingleton(() => CreateOrderUsecase(locator()));
  locator.registerLazySingleton(() => GetUserOrdersUsecase(locator()));
  locator.registerLazySingleton(() => GetCompanyStreamsUsecase(locator()));
  locator.registerLazySingleton(() => GetStatisticsUsecase(locator()));
}
